jsool.namespace("js.flux.laf");

js.flux.laf.Soft = {
	FONT_COLOR: '#000000',
	FONT_FACE: 'Tahoma',
	FONT_SIZE: 12,
	
	BUTTON_BODY_COLOR: '#F1F1F1',
	BUTTON_BODY_PRESSED: '#EBEBEB',
	BUTTON_BORDER_COLOR: '#707070',
	BUTTON_BORDER_FOCUS: '#B7C9E5',
	BUTTON_BORDER_OVER: '#D3DBEA',
	BUTTON_BORDER_RADIUS: 2,
	BUTTON_BORDER_WIDTH: 1,
	
	CONTAINER_BODY_COLOR: '#FFFFFF',
	CONTAINER_BORDER_COLOR: '#898C95',
	CONTAINER_BORDER_RADIUS: 2,
	CONTAINER_BORDER_WIDTH: 1,
	
	CHECKBOX_CHECK: "#D3DBEA",
	
	SELECTION: "#C8E9FB"
};