var jsool=function(){var a=[],b=[],d=false,e=false,h={},i=0;h.namespace=function(f){f=f.split(/\./);for(var j,k=window,l=0,m;m=f[l++];){j=k[m];if(typeof j==="undefined")k[m]={};k=k[m]}};h.doReady=function(){for(var f=0;f<b.length;f++)try{b[f]()}catch(j){if(typeof console!="undefined"){console.error(j.message||j.toString());console.info(j)}else{alert(j.description||j.toString());throw j;}}};h.prepareSystem=function(){for(var f=0;f<a.length;f++)a[f]()};if(window.addEventListener)window.addEventListener("load",
function(){jsool.start();delete jsool.start;window.removeEventListener("load",arguments.callee,false)},false);else window.onload=function(){jsool.start();delete jsool.start;window.onload=null};return{onReady:function(f){b.push(f);this.isReady()&&f.call(jsool,[])},onSystemReady:function(f){a.push(f);this.isReady()&&f.call(jsool,[])},time:function(){return+new Date},start:function(){d=true;h.prepareSystem();e=true;h.doReady()},isReady:function(){return e&&d},emptyFn:function(){},apply:function(f,j,
k){k&&jsool.apply(f,k);if(f&&j&&typeof j=="object")for(var l in j)f[l]=j[l];return f},applyIf:function(f,j){if(f)for(var k in j)jsool.isDefined(f[k])||(f[k]=j[k]);return f},copy:function(f){if(typeof f==="object"){var j;j=f.cls?new f.cls:{};jsool.apply(j,f)}return j},iterate:function(f,j){for(var k in f)typeof f[k]!=="function"&&j(k,f[k])},id:function(f){f.id=f.id||"jsool-"+i++;return f.id},isDefined:function(f){return typeof f!=="undefined"},isArray:function(f){return f.constructor==Array},isObject:function(f){return typeof f===
"object"},isNumber:function(f){return typeof f==="number"},isBoolean:function(f){return typeof f==="boolean"},isDate:function(f){return f.constructor==Date},isFunction:function(f){return typeof f==="function"},namespace:h.namespace}}();
jsool.$extends=function(a,b,d){var e;if(typeof a!="function")return null;if(b.cons&&typeof b.cons=="function"){e=function(j,k){j=b.cons;k=a;return function(){k.apply(this,arguments);j.apply(this,arguments)}}();delete b.cons}else if(b.ccons&&typeof b.ccons=="function"){e=function(){var j=b.ccons;return function(){j.apply(this,arguments)}}();delete b.ccons}else e=function(){return function(){a.apply(this,arguments)}}();for(var h in a.prototype)e.prototype[h]=a.prototype[h];if(jsool.isIE)e.prototype.toString=
a.prototype.toString;for(var i in b)e.prototype[i]=b[i];h=function(){return function(){a.apply(this,arguments)}}();for(var f in a.prototype)if(typeof a.prototype[f]=="function")h[f]=function(){var j=a.prototype[f];return function(){return j.apply(this,arguments)}}();e.prototype.supercls=a;e.prototype.$super=h;e.prototype.type=d;return e.prototype.cls=e};var $extends=jsool.$extends;Number.prototype.instanceOf=function(a){return a==Number||typeof a=="number"};Number.prototype.type="Number";Number.prototype.cls=Number;Number.prototype.supercls=Object;Number.isNumber=function(a){return typeof a=="number"};jsool.namespace("js.core");js.core.Number=Number;jsool.applyIf(String.prototype,{replaceAll:function(a,b){for(var d=this,e=d.indexOf(a);e>-1;){d=d.replace(a,b);e=d.indexOf(a)}return d},toCharArray:function(){for(var a=[],b=0;b<this.length;b++)a.push(this[b]);return a},trim:function(){return this.replace(/^\s*([\S\s]*?)\s*$/,"$1")},hash:0,hashCode:function(){var a=this.hash;if(a==0){for(var b=0,d=0;d<this.length;d++)a=31*a+this.charCodeAt(b++);this.hash=a}return a},instanceOf:function(a){return a==String||a==js.core.Object},substr:function(a,b){if(b==
null)b=this.length-a;return substring(this,a+1,b)},lastIndexOf:function(a,b){size=a.length;b==null?b=this.length-size+1:++b;if(a.length==0)return b-1;for(;b>=0&&substring(this,b--,size)!=a;);return b==-1?-1:b}});String.isString=function(a){return typeof a=="string"};
String.decodeHTML=function(a){var b=RegExp("&#[0-9]{1,3};","g");if(b=a.match(b))for(var d=function(i){i=i.substring(2);i=i.substring(0,i.length-1);i=window.parseInt(i,10);return String.fromCharCode(i)},e=0;e<b.length;e++){var h=d(b[e]);a=a.replace(b[e],h)}return a};String.encodeHTML=function(a){for(var b=[],d=0;d<a.length;d++){var e=a.charAt(d);e>="a"&&e<="z"||e>="A"&&e<="Z"||e>="0"&&e<="9"?b.push(e):b.push("&#"+a.charCodeAt(d)+";")}return b.join("")};jsool.namespace("js.core");js.core.String=String;Array.isArray=function(a){return a.constructor==Array};Array.iterate=function(a,b){for(var d=0,e;e=a[d++];)b(d,e)};
jsool.applyIf(Array.prototype,{shuffle:function(){this.sort(function(){return Math.random()>0.5?1:-1})},instanceOf:function(a){return a==Array},forEach:function(a){for(var b=this.length,d=0;d<b;d++)a(this[d])},every:function(a){for(var b=this.length;b--;)if(!a(this[b]))return false;return true},filter:function(a){for(var b=this.length,d=[],e=0;e<b;e++)a(this[e])&&d.push(this[e]);return d},map:function(a){for(var b=this.length,d=[],e=0;e<b;e++)d.push(a(this[e]));return d},indexOf:function(a,b){var d=
this.length>>>0,e=Number(b)||0;e=e<0?Math.ceil(e):Math.floor(e);if(e<0)e+=d;for(;e<d;e++)if(e in this&&this[e]===a)return e;return-1},clone:function(){for(var a=[],b=0,d;d=this[b++];)a.push(d);return a},concat:function(a){for(var b=[],d,e=0;d=this[e++];)b.push(d);for(e=0;d=a[e++];)b.push(d);return b},remove:function(a){for(var b=0;b<this.length;b++)a==this[b]&&this.slice(b,1)},contains:function(a){return this.indexOf(a)>=0}});Array.MAX_LENGTH=4294967295;jsool.namespace("js.core");js.core.Array=Array;jsool.namespace("js.core");js.core.Object=function(){};
js.core.Object.prototype={hash:0,type:"js.core.Object",cls:js.core.Object,supercls:js.core.Object,hashCode:function(){if(this.hash==0)this.hash=Math.round(Math.random()*1E3)+(new Date).getTime();return this.hash},equals:function(a){if(a==null)return false;if(typeof a!="object")return false;for(var b in this)if(this[b]!=a[b])return false;return true},toString:function(){return this.type+"@"+this.hashCode()},instanceOf:function(a){if(a==js.core.Object)return true;else if(this.cls==a)return true;else{var b=
this.cls.prototype.supercls;do{if(b==a)return true;b=b.prototype.supercls}while(b!=js.core.Object);return false}},clone:function(){var a=new this.supercls;jsool.apply(a,this);return a}};Object.isObject=function(a){return typeof a==="object"};js.core.Browser={init:function(){this.browser=this.searchString(this.dataBrowser)||"An unknown browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"an unknown version";this.OS=this.searchString(this.dataOS)||"an unknown OS";jsool.isIE=this.browser=="Explorer";jsool.isFF=this.browser=="Firefox";jsool.isOpera=this.browser=="Opera";jsool.isChrome=this.browser=="Chrome";jsool.isSafari=this.browser=="Safari";jsool.isWebKit=jsool.isChrome||jsool.isSafari},
searchString:function(a){for(var b=0;b<a.length;b++){var d=a[b].string,e=a[b].prop;this.versionSearchString=a[b].versionSearch||a[b].identity;if(d){if(d.indexOf(a[b].subString)!=-1)return a[b].identity}else if(e)return a[b].identity}},searchVersion:function(a){var b=a.indexOf(this.versionSearchString);if(b!=-1)return parseFloat(a.substring(b+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",
versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,
subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],dataOS:[{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]};
js.core.Browser.init();jsool.namespace("js.core");
js.core.Exception=$extends(js.core.Object,{cons:function(a,b,d,e){if(a==null)throw Error("The Exception message must not be null");this.message=a;this.source=b;this.method=d;this.cause=e},message:null,source:null,method:null,cause:null,getMethod:function(){if(!this.source)return"";var a=this.source.cls.prototype,b=this.method.callee,d;for(var e in a)if(a[e]==b)d="."+e+"(";a=[];for(b=0;b<this.method.length;b++)typeof this.method[b]=="object"?a.push(this.method[b].type||this.method[b]):a.push(this.method[b]);
return d+a.join(",")+")"},toString:function(){var a;if(this.source){a=this.source.type;if(this.method)a+=this.getMethod()}else a=this.type;a=a+": "+this.message;if(this.cause)a=a+"\n"+this.cause.toString();return a}},"js.core.Exception");jsool.namespace("js.core");
js.core.EventManager=function(){function a(i,f,j,k){var l=jsool.id(i);l=h[l]=h[l]||{};l=l[f]=l[f]||[];k=k||i;var m=function(o){o=o||window.event;j.call(k,o)};l.push({EVENT:f,FUNCTION:j,HANDLER:m,ELEMENT:i,SCOPE:k});jsool.isIE?i.attachEvent("on"+f,m):i.addEventListener(f,m,false);return true}function b(i,f,j){jsool.isIE?i.detachEvent("on"+f,j):i.removeEventListener(f,j,false)}function d(i,f,j){var k=jsool.id(i),l=h[k][f];if(j)for(var m=0,o;o=l[m++];){if(o.FUNCTION==j){b(i,f,o.HANDLER);delete h[k][f][m]}}else{for(m=
0;o=l[m++];)b(i,f,o.HANDLER);delete h[k][f]}}function e(i){var f=jsool.id(i);jsool.iterate(h[f],function(j,k){Array.iterate(k,function(l,m){b(i,j,m.HANDLER);delete h[f][j][l]});delete h[f][j]})}var h={};return{on:a,addListener:a,un:d,removeListener:d,destroy:e,detroyListeners:e,isDomEvent:function(i){return i.match(domEventsRe)!=null}}}();jsool.namespace("js.util");js.util.Collection=$extends(js.core.Object,{add:jsool.emptyFn,addAll:function(a){for(a=a.iterator();a.hasNext();)this.add(a.next())},contains:jsool.emptyFn,isEmpty:function(){return this.size()==0},size:jsool.emptyFn,iterator:jsool.emptyFn,remove:jsool.emptyFn,toArray:jsool.emptyFn},"js.util.Collection");jsool.namespace("js.util");
js.util.MixedCollection=$extends(js.util.Collection,{cons:function(){this.map={};this.data=[];this.keys=[]},map:null,data:null,keys:null,add:function(a,b){if(!String.isString(a))throw new js.core.Exception("Illegal argument: "+a,this,arguments);this.map[a]=b;this.data.push(b);this.keys.push(a)},get:function(a){if(typeof a==="number")return this.map[this.keys[a]];else if(typeof a==="string")return this.map[a];return null},addAll:function(a){for(a=a.iterator();a.hasNext();)this.add(a.next())},contains:function(a){return this.data.indexOf(a)!=
-1},isEmpty:function(){return this.size()==0},size:function(){return this.data.length},iterator:function(){return new js.util.ArrayList.Iterator(this.data)},remove:function(a){this.keys.remove(this.keys[this.data.indexOf(a)]);this.data.remove(a);for(var b in this.map)if(this.map[b]==a){delete this.map[b];return}},toArray:function(){return this.data.clone()}},"js.util.MixedCollection");jsool.namespace("js.util");js.util.List=$extends(js.util.Collection,{get:jsool.emptyFn,clear:jsool.emptyFn,indexOf:jsool.emptyFn},"js.util.List");jsool.namespace("js.util");
js.util.ArrayList=$extends(js.util.List,{cons:function(a){this.data=[];if(a!=null)if(Array.isArray(a))this.addAll(a);else typeof a=="object"&&a.instanceOf(js.util.Collection)&&this.addAll(a)},data:null,_size:0,indexOf:function(a){if(typeof a=="object")for(var b=0;b<this._size;b++){if(a.equals(this.data[b]))return b}else return this.data.indexOf(a);return-1},lastIndexOf:function(a){if(a==null)for(var b=this._size-1;b>=0;b--){if(this.data[b]==null)return b}else if(typeof a=="object")for(b=this._size-
1;b>=0;b--){if(a.equals(this.data[b]))return b}else for(b=this._size-1;b>=0;b--)if(a==this.data[b])return b;return-1},clone:function(){var a=new js.util.ArrayList;a.addAll(this.data);return a},toArray:function(){return this.data.clone()},get:function(a){if(a>=this._size)throw new js.core.Exception("Array Index Out Of Bounds",this,arguments);return this.data[a]},add:function(a,b){if(b==null){this.data.push(a);this._size++}else{if(typeof b!="number")throw new js.core.Exception("Invalid argument type: "+
typeof number,this,arguments);if(b>=this._size)throw new js.core.Exception("Array index out of bounds: "+number,this,arguments);this.data.splice(b,0,a)}},remove:function(a){if(a>=this.length||a<0)throw new js.core.Exception("Array index out of bounds: "+a,this,arguments);this.data.splice(a,1)},clear:function(){delete this.data;this.data=[];this._size=0},addAll:function(a){if(a.instanceOf&&a.instanceOf(js.util.Collection))for(a=a.iterator();a.hasNext();){this.data.push(a.next());this._size++}else{var b=
this;Array.iterate(a,function(d,e){b.data.push(e);b._size+=1})}},size:function(){return this._size},iterator:function(){return new js.util.ArrayList.Iterator(this.data)},contains:function(a){return this.indexOf(a)>=0}},"js.util.ArrayList");
js.util.ArrayList.Iterator=$extends(js.core.Object,{cons:function(a){js.core.Object.apply(this,arguments);this.size=a.length;this.list=a},size:0,index:0,list:null,hasNext:function(){return this.index<this.size},next:function(){if(!this.hasNext())throw new js.core.Exception("Array Index Out Of Bounds: "+this.index,this,arguments);var a=this.list[this.index];this.index++;return a},nextIndex:function(){return this.index}},"js.util.ArrayList.Iterator");jsool.namespace("js.util");
js.util.LinkedList=$extends(js.util.List,{cons:function(){this.header={element:null,next:null,previous:null};this.header.next=this.header.previous=this.header},header:null,last:null,_size:0,_newEntry:function(a,b,d){return{element:a,next:b,previous:d}},_addBefore:function(a,b){var d=this._newEntry(a,b,b.previous);d.previous.next=d;d.next.previous=d;this._size++},_entry:function(a){if(a<0||a>=this._size)throw new js.core.Exception("Index Out Of Bounds: "+a,this,arguments);var b=this.header;if(a<this._size>>
1)for(var d=0;d<=a;d++)b=b.next;else for(d=this._size;d>a;d--)b=b.previous;return b},_remove:function(a){if(a==this.header)throw new js.core.Exception("No Such Element",this,arguments);a.previous.next=a.next;a.next.previous=a.previous;a.next=a.previous=null;a.element=null;this._size--},add:function(a,b){if(b==null)this._addBefore(a,this.header);else{if(typeof b!="number")throw new js.core.Exception("Invalid argument type: "+typeof number,this,arguments);if(b>=this._size)throw new js.core.Exception("Array index out of bounds: "+
number,this,arguments);this._addBefore(a,b==this._size?this.header:this._entry(b))}},get:function(a){return this._entry(a).element},set:function(a,b){this._entry(b).element=a},remove:function(a){if(typeof a=="number")this._remove(this._entry(a));else if(typeof a=="object")for(var b=this.header.next;b!=this.header;b=b.next)a==b.element&&this._remove(b)},clear:function(){for(var a=this.header.next;a!=this.header;){var b=a.next;a.next=a.previous=null;a.element=null;a=b}this.header.next=this.header.previous=
this.header;this._size=0},addAll:function(a){if(a.iterator)for(a=a.iterator();a.hasNext();)this.add(a.next());else for(var b=0;b<a.length;b++)this.add(a[b])},toArray:function(){for(var a=[],b=this.header.next;b!=this.header;b=b.next)a.push(b.element);return a},indexOf:function(a){for(var b=0,d=this.header.next;d!=this.header;d=d.next){if(a==d.element)return b;b++}return-1},contains:function(a){return this.indexOf(a)!=-1},iterator:function(){return new js.util.LinkedList.Iterator(this)},size:function(){return this._size},
clone:function(){var a=new js.util.LinkedList;a.addAll(this);return a}},"js.util.LinkedList");
js.util.LinkedList.Iterator=$extends(js.core.Object,{cons:function(a){js.core.Object.apply(this,arguments);this.size=a._size;this.nextNode=a.header.next;this.header=a.header},size:0,nextNode:null,header:null,index:0,hasNext:function(){return this.nextNode!=this.header},next:function(){if(!this.hasNext())throw new js.core.Exception("No Such Element",this,arguments);var a=this.nextNode;this.nextNode=a.next;this.index++;return a.element},nextIndex:function(){return this.index+1}},"js.util.LinkedList.Iterator");jsool.namespace("js.util");
js.util.HashSet=$extends(js.util.Collection,{cons:function(){this.set={}},set:null,_size:0,add:function(a){var b=typeof a;if(b=="object"&&a.hashCode)b=a.hashCode();else if(b=="number"||b=="string")b=a.toString();else throw new js.core.Exception("Invalid argument type: "+a.toString(),this,arguments);this.set[b]||this._size++;this.set[b]=a},mapCode:function(a){return typeof a=="object"&&a.hashCode?a.hashCode():a.toString()},addAll:function(a){if(a.instanceOf(js.util.Collection))for(a=a.iterator();a.hasNext();)this.add(a.next());
else if(Array.isArray(a))for(var b=0;b<a.length;b++)this.add(a[b])},contains:function(a){if(a=="toString")return null;return this.set[this.mapCode(a)]!=null},clear:function(){this._size=0;this.set={}},remove:function(a){delete this.set[this.mapCode(a)]&&this._size--},size:function(){return this._size},toArray:function(){var a=[];for(var b in this.set)a.push(this.set[b]);return a},iterator:function(){return new js.util.HashSet.Iterator(this.set)}},"js.util.HashSet");
js.util.HashSet.Iterator=$extends(js.core.Object,{constructor:function(a){js.core.Object.apply(this,arguments);this.data=[];for(var b in a){this.data.push(b);this.size++}},data:null,index:0,size:0,hasNext:function(){return this.index<this.size},next:function(){if(!this.hasNext())throw new js.core.Exception("Array Index Out of Bounds: "+this.index,this,arguments);var a=this.data[this.index];this.index++;return a},nextIndex:function(){return this.hasNext()?this.index+1:-1}},"js.util.HashSet.Iterator");jsool.namespace("js.util");js.util.Map=$extends(js.core.Object,{containsKey:jsool.emptyFn,containsValue:jsool.emptyFn,size:jsool.emptyFn,clear:jsool.emptyFn,put:jsool.emptyFn,get:jsool.emptyFn,isEmpty:function(){return this.size()<=0}},"js.util.Map");jsool.namespace("js.util");
js.util.HashMap=$extends(js.util.Map,{cons:function(){this.map={};this.keys={}},values:null,map:null,_size:0,keys:null,put:function(a,b){var d=typeof a;if(d=="object"&&a.hashCode)d=a.hashCode();else if(d=="number"||d=="string")d=a.toString();else throw new js.core.Exception("Invalid argument type: "+a.toString(),this,arguments);d in this.keys&&this._size--;this._size++;this.keys[d]=d;this.map[d]=b;return true},containsKey:function(a){return this.mapCode(a)in this.keys},containsValue:function(a){for(var b in this.map)if(this.map[b]==
a)return true;return false},get:function(a){return this.map[this.mapCode(a)]},size:function(){return this._size},remove:function(a){if(this.get(a)==null)return false;delete this.map[this.mapCode(a)];this._size--;return true},mapCode:function(a){return typeof a=="object"&&a.hashCode?a.hashCode():a.toString()},contains:function(a){return this.containsValue(a)},clear:function(){this._size=0;this.map={}}},"js.util.HashMap");jsool.namespace("js.util");
js.util.ReferenceMap=$extends(js.util.Map,{cons:function(){this.keys=new js.util.LinkedList;this.values=new js.util.LinkedList},values:null,keys:null,put:function(a,b){var d=this.keys.indexOf(a);if(d>=0)this.values.add(b,d);else{this.keys.add(a);this.values.add(a)}},containsKey:function(a){return this.keys.contains(a)},containsValue:function(a){return this.values.contains(a)},size:function(){return this.keys.size()},clear:function(){this.keys.clear();this.values.clear()},get:function(a){a=this.keys.indexOf(a);
return a<0?null:this.values.get(a)}},"js.util.ReferenceMap");jsool.namespace("js.util");
js.util.StringBuilder=$extends(js.core.Object,{cons:function(a){this.buffer=[];a&&this.append(a)},_length:0,buffer:null,append:function(a){a=String(a);this.buffer.push(a);this._length+=a.length;return this},clear:function(){this.buffer=[]},toString:function(){return this.buffer.join("")},deleteCharAt:function(a){if(typeof a!="number")throw new js.core.Exception("Invalid argument type",this,arguments);if(a>this._length||a<0)throw new js.core.Exception("Array out of bounds",this,arguments);var b=this.buffer.join("");
this.clear();if(a==0)this.append(b.substring(1));else if(a==this._length)this.append(b.substring(0,this._length-1));else{this.append(b.substring(0,a));this.append(b.substring(a+1))}},length:function(){return this._length}},"js.util.StringBuilder");jsool.namespace("js.util");js.util.Locale=$extends(js.core.Object,{cons:function(a){for(var b=this.cache.length,d=0;d<b;d++)if(this.cache[d].language==a)return this.cache[d];this.language=a;this.cache.push(this)},cache:[],language:null,weekdays:null,months:null,datePattern:null},"js.util.Locale");js.util.Locale.DEFAULT=null;
jsool.onSystemReady(function(){var a=js.util.Locale,b=new js.util.Locale("en-US");b.weekdays=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];b.months=["January","February","March","April","May","June","July","August","September","October","November","December"];b.datePattern="MM/dd/yyyy";a.USA=b;b=new js.util.Locale("pt-BR");b.weekdays=["Domingo","Segunda-feira","Terca-feira","Quarta-feira","Quinta-feira","Sexta-feira","Sabado"];b.months=["Janeiro","Fevereiro","Marco","Abril",
"Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];b.datePattern="dd/MM/yyyy";a.BRAZIL=b;js.util.Locale.DEFAULT=a.USA});jsool.namespace("js.util");js.util.Serializable=$extends(js.core.Object,{serialize:function(){var a=this.cls.prototype,b=new js.util.StringBuilder,d;b.append("{");for(var e in a){d=typeof a[e];if(d=="string")b.append(e).append(': "').append(a[e]).append('",');else if(d=="number")b.append(e).append(": ").append(a[e]).append(",");else if(d=="boolean")b.append(e).append(": ").append(a[e]?"TRUE":"FALSE").append(",")}b.deleteCharAt(b.length());b.append("}");return b.toString()}},"js.util.Serializable");jsool.namespace("js.util");
js.util.Observable=$extends(js.core.Object,{events:null,addEvent:function(){var a=arguments;if(!this.events)this.events={};if(Array.isArray(a[0])){a=a[0];for(var b=0,d;d=a[b++];)this.events[d]=true}else if(a.length>1){var e=this;Array.iterate(a,function(h,i){i in e.events||(e.events[i]=true)})}else if(a.length==1&&!this.events[a[0]])this.events[a[0]]=true},on:function(a,b,d){if(this.events){if(String.isString(a)){var e={};e[a]=b;e.scope=d||this;a=e}d=a.scope?a.scope:this;for(var h in a)if(this.events[h]){b=
this.events[h];if(!b){b=[];this.events[h]=b}b.push({scope:d,func:a[h]})}}},fireEvent:function(){if(this.events){var a=arguments,b,d,e;if(typeof a[0]==="string"){b=a[0];a=Array.prototype.slice.apply(a,[1])}else b=a[0].type;d=this.events[b];if(d!=null)for(var h=0;h<d.length;h++){e=d[h];window.setTimeout(function(){e.func.apply(e.scope,a)},0)}b="on"+b;typeof this[b]==="function"&&this[b].apply(this,a)}},destroyListeners:function(){delete this.events}},"js.util.Observable");jsool.namespace("js.util");
js.util.DateFormat=$extends(js.core.Object,{cons:function(a,b){this.setLocale(b?b:js.util.Locale.DEFAULT);this.pattern=a?a:this.pattern;this.patternKeyMap=new js.util.HashMap;for(var d=0,e;e=this.patterns[d++];)this.patternKeyMap.put("{"+e.key+"}",e)},pattern:"yyyy/mm/dd",locale:null,compiled:null,weekdays:null,months:null,patternKeyMap:null,format:function(a){for(var b=new String(this.pattern),d,e=this.patterns.length,h=0;h<e;h++){d=this.patterns[h];if(b.search(d.pattern)>=0)b=b.replace(d.pattern,
this["get"+d.name](a))}return b},setLocale:function(a){if(!a.instanceOf(js.util.Locale))throw new js.core.Exception("Invalid argument: "+a,this,arguments);this.locale=a;this.months=a.months;this.weekdays=a.weekdays;this.pattern=a.datePattern;this.compiled=null},compile:function(){for(var a=new String(this.pattern),b,d=this.patterns.length,e=0;e<d;e++){b=this.patterns[e];a=a.replace(b.pattern,"{"+b.key+"}")}this.compiled=a},parse:function(a){if(!String.isString(a))throw new js.core.Exception("invalid argument type: "+
a,this,arguments);this.compiled||this.compile();var b=new Date,d,e,h=this.compiled;for(a=a.toLowerCase();(d=h.indexOf("{"))>=0;){e=h.indexOf("}")+1;a=a.substring(d);d=this.patternKeyMap.get(h.substring(d,e));a=this["parse"+d.name](a,b);h=h.substring(e)}return b},patterns:[{pattern:/y{3,}/,key:"0",name:"LongYear"},{pattern:/y{1,2}/,key:"1",name:"ShortYear"},{pattern:/M{4,}/,key:"2",name:"LongMonth"},{pattern:/M{3}/,key:"3",name:"ShortMonth"},{pattern:/M{2}/,key:"4",name:"LongNumericMonth"},{pattern:/M{1}/,
key:"5",name:"ShortNumericMonth"},{pattern:/d{2,}/,key:"6",name:"LongDay"},{pattern:/d/,key:"7",name:"ShortDay"},{pattern:/E{4,}/,key:"8",name:"LongWeekday"},{pattern:/E{1,3}/,key:"9",name:"ShortWeekday"}],getLongYear:function(a){return new String(a.getFullYear())},getShortYear:function(a){return(new String(a.getFullYear())).substring(2)},getLongMonth:function(a){return this.months[a.getMonth()]},getShortMonth:function(a){return this.months[a.getMonth()].substring(0,3)},getLongNumericMonth:function(a){a=
new String(a.getMonth()+1);return a.length<2?"0"+a:a},getShortNumericMonth:function(a){return new String(a.getMonth()+1)},getLongDay:function(a){a=new String(a.getDate());return a.length<2?"0"+a:a},getShortDay:function(a){return new String(a.getDate())},getLongWeekday:function(a){return this.weekdays[a.getDay()]},getShortWeekday:function(a){return this.weekdays[a.getDay()].substring(0,3)},parseLongYear:function(a,b){var d=a.substring(0,4);b.setYear(parseInt(d));return a.substring(4)},parseShortYear:function(a,
b){var d=a.substring(0,2);d=(new Date).getFullYear().toString().substring(0,2)+d;b.setYear(parseInt(d));return a.substring(2)},parseLongMonth:function(a,b){for(var d=0;a.indexOf(this.months[d].toLowerCase())!=0;)d++;b.setMonth(d);return a.substring(this.months[d].length)},parseShortMonth:function(a,b){for(var d=0;a.indexOf(this.months[d].substring(0,3).toLowerCase())!=0;)d++;b.setMonth(d);return a.substring(3)},parseLongNumericMonth:function(a,b){var d=a.substring(0,2);b.setMonth(window.parseInt(d)-
1);return a.substring(2)},parseShortNumericMonth:function(a,b){var d=false;try{var e=window.parseInt(a.substring(0,2));d=a.charCodeAt(1)<48||a.charCodeAt(1)>57}catch(h){d=true}if(d||e>12){e=window.parseInt(a.substring(0,1));b.setMonth(e-1);return a.substring(1)}else{b.setMonth(e-1);return a.substring(2)}},parseLongDay:function(a,b){var d=a.substring(0,2);b.setDate(window.parseInt(d));return a.substring(2)},parseShortDay:function(a,b){var d=false;try{var e=window.parseInt(a.substring(0,2));d=a.charCodeAt(1)<
48||a.charCodeAt(1)>57}catch(h){d=true}if(d||e>31){e=window.parseInt(a.substring(0,1));b.setDate(e);return a.substring(1)}else{b.setDate(e);return a.substring(2)}}},"js.util.DateFormat");jsool.namespace("js.dom");js.dom.Template=$extends(js.core.Object,{cons:function(){var a=arguments;if(Array.isArray(a[0]))this.html=a[0].join("");else if(a.length>1){var b=[];Array.iterate(a,function(d,e){b.push(e)});this.html=b.join("")}else if(String.isString(a[0]))this.html=a[0]},propertyRe:/\{([\w-]+)\}/g,html:null,compile:function(a){return this.html.replace(this.propertyRe,function(b,d){return jsool.isDefined(a[d])?a[d]:""})}},"js.dom.Template");jsool.namespace("js.dom");
js.dom.Helper=function(){function a(h){if(!e){e=document.getElementById("jsool-proxy");if(!e){e=b.createElement("div");e.style.display="none";e.innerHTML="";e.id="jsool-proxy";d=b.getElementsByTagName("body")[0]}}d.appendChild(e);e.innerHTML=h;var i=b.createDocumentFragment();Array.iterate(e.childNodes,function(f,j){j.nodeType==1&&i.appendChild(j)});e.innerHTML="";d.removeChild(e);return i}var b=window.document,d,e;return{createDom:function(h,i){var f;if(String.isString(h))f=a(h);else if(Array.isArray(h)){f=
b.createDocumentFragment();h.forEach(function(j){js.dom.Helper.createDom(j,f)})}else if(Object.isObject(h)){f=b.createElement(h.tag||"div");jsool.iterate(h,function(j,k){/tag|style|html|children/.test(j)||(f[j]=k)});h.style&&js.dom.Helper.applyStyle(f,h.style);if(h.children)js.dom.Helper.createDom(h.children,f);else if(h.html)f.innerHTML=h.html}if(i)i.append?i.append(f):i.appendChild(f);return f},applyStyle:function(h,i){if(h.nodeType&&i){var f=h.style;jsool.iterate(i,function(j,k){if(typeof k!==
"undefined")f[j]=k})}}}}();jsool.namespace("js.dom");
js.dom.Element=$extends(js.core.Object,{cons:function(a){var b=typeof a;if(b=="string")this.dom=document.createElement(a);else if(b=="object"&&a.tagName)this.dom=a;else throw new js.core.Exception("Invalid tag: "+a,this);this.id=jsool.id(this.dom);js.dom.Element.cache(this)},dom:null,parent:null,getDom:function(){return this.dom},set:function(a,b){if(typeof a=="string")this.dom[a]=b;else if(typeof a=="object")for(var d in a)this.dom[d]=a[d]},get:function(a){return this.dom[a]},getId:function(){return this.id},
append:function(a){var b=typeof a;if(b==="string")this.dom.innerHTML+=a;else if(b==="object")if(a.nodeType)this.dom.appendChild(a);else if(a.instanceOf(js.dom.Element)){a.parent&&a.parent.remove(a);this.dom.appendChild(a.getDom());a.parent=this}},setText:function(a){this.dom.innerHTML="";this.dom.appendChild(document.createTextNode(String.isString(a)?a:new String(a)))},getText:function(){return this.dom.innerHTML},setHtml:function(a){this.dom.innerHTML=String.isString(a)?a:new String(a)},getHtml:function(){return this.dom.innerHTML},
tag:function(){return this.dom.tagName},remove:function(a){a.nodeType||(a=a.getDom());this.getDom().removeChild(a)},on:function(a,b,d){js.core.EventManager.on(this.dom,a,b,d||this)},un:function(a,b){a?js.core.EventManager.un(this.dom,a,b):js.core.EventManager.destroy(this.dom)},destroyListeners:function(){js.core.EventManager.destroy(this.dom)},setClass:function(a){if(typeof a==="string")this.dom.className=a},addClass:function(a){if(a)this.dom.className+=" "+a.trim()},removeClass:function(a){this.dom.className=
this.dom.className.replace(RegExp("\\b"+a.trim()+"\\b","g"),"")},applyStyle:function(a,b){var d=this.dom.style;if(typeof a=="string")d[a]=b;else if(typeof a=="object")for(var e in a)d[e]=a[e]},children:function(){return Raze.query("*",this.dom)},getPosition:function(){for(var a=this.dom,b=0,d=0;a!=null;){b+=a.offsetTop;d+=a.offsetLeft;a=a.offsetParent}return{y:b,x:d}},getBox:function(){var a=this.getPosition(),b=this.dom;a.w=b.clientWidth;a.h=b.clientHeight;return a},getWidth:function(){return this.dom.clientWidth},
getHeight:function(){return this.dom.clientHeight},getParent:function(){return jsool.get(this.dom.parentNode)},destroy:function(){this.getParent()!=null&&this.getParent().remove(this);this.dom.parentNode&&this.dom.parentNode.removeChild(this.dom);this.destroyListeners();for(var a in this.dom)try{this.dom[a]=null}catch(b){}js.dom.Element.unCache(this);delete this.dom},query:function(a,b){return b?Raze.query(a,this.getDom()):js.dom.Element.select(a)},setOpacity:function(a){var b=this.dom.style;if(jsool.isIE)b.filter=
"alpha(opacity="+a*100+")";else b.opacity=a}},"js.dom.Element");js.dom.Element.attributes={"class":"className"};
jsool.onSystemReady(function(){var a=new js.util.HashMap,b=js.dom.Element;b.get=function(d){if(typeof d=="string"){var e=a.get(d);if(e)return e;if(d=document.getElementById(d))return new js.dom.Element(d)}else if(typeof d=="object"&&d.nodeType){if(d.id){e=b.get(d.id);if(e!=null)return e}return new js.dom.Element(d)}return null};jsool.get=b.get;b.cache=function(d){if(d.instanceOf(b)){a.put(d.getId(),d);return true}return false};b.unCache=function(d){if(d.instanceOf(EL)){a.remove(d);return true}return false};
b.query=function(d,e){return Raze.query(d,e)};jsool.query=b.query;b.queryNode=function(d,e){return Raze.queryNode(d,e)};jsool.queryNode=b.queryNode;b.BODY=new js.dom.Element(Raze.queryNode("body"));if(jsool.isIE)b.BODY.addClass("ie");else if(jsool.isFF)b.BODY.addClass("ff");else jsool.isOpera&&b.BODY.addClass("opera")});jsool.namespace("js.dom");
js.dom.CompositeElement=$extends(js.core.Object,{cons:function(a){this.elements=a},elements:[],add:function(a){this.elements.addAll(a)},size:function(){return this.elements.size()},clear:function(){this.elements.clear()},each:function(a,b){for(var d,e=0,h=[];d=this.elements[e++];)h.push(a.apply(b||d,[d]));return h},first:function(){return this.elements[0]},item:function(a){return this.elements[a]},set:function(a,b){var d=this;typeof a==="object"?jsool.iterate(a,function(e,h){Array.iterate(d.elements,
function(i,f){f[e]=h})}):Array.iterate(d.elements,function(e,h){h[a]=b});return this},on:function(a,b){var d=js.core.EventManager;Array.iterate(this.elements,function(e,h){d.on(h,a,b,h)});return this},un:function(a,b){var d=js.core.EventManager;Array.iterate(this.elements,function(e,h){d.un(h,a,b,h)});return this},addClass:function(a){var b=RegExp("\\b"+a+"\\b",g);Array.iterate(this.elements,function(d,e){e.className.match(b)||(e.className+=a.trim())});return this},setClass:function(a){Array.iterate(this.elements,
function(b,d){d.className=a.trim()});return this},removeClass:function(a){var b=RegExp("\\b"+a.trim()+"\\b");Array.iterate(this.elements,function(d,e){e.className=e.className.replace(b,"")});return this},setText:function(a){var b=document.createTextNode(a);Array.iterate(this.elements,function(d,e){e.innerHTML="";e.appendChild(b.cloneNode())});return this},applyStyle:function(a,b){if(typeof a=="string")Array.iterate(this.elements,function(d,e){e.style[a]=b});else typeof a=="object"&&Array.iterate(this.elements,
function(d,e){var h=e.style;jsool.iterate(a,function(i,f){h[i]=f})});return this}},"js.dom.CompositeElement");js.dom.Element.select=function(a,b){var d=Raze.query(a,b);return new js.dom.CompositeElement(d)};jsool.select=js.dom.Element.select;jsool.namespace("js.canvas");
js.canvas.Canvas=$extends(js.dom.Element,{ccons:function(){this.$super("canvas")},getContext:function(){var a=this.dom.getContext("2d"),b=Math.PI,d=Math.PI*2,e=Math.PI/2,h=3*(Math.PI/2);jsool.apply(a,{clear:function(){var i=this.canvas.getAttribute("width"),f=this.canvas.getAttribute("height");this.clearRect(0,0,i,f)},getHeight:function(){return this.canvas.getAttribute("height")},getWidth:function(){return this.canvas.getAttribute("width")},fillRoundRect:function(i,f,j,k,l){var m=i+l,o=i+j,r=f+l;
k=f+k;this.beginPath();this.arc(m,r,l,b,h,false);this.lineTo(j-l+i,f);this.arc(o-l,r,l,h,d,false);this.lineTo(o,k-l);this.arc(o-l,k-l,l,d,e,false);this.lineTo(m,k);this.arc(m,k-l,l,e,b,false);this.lineTo(i,r);this.fill()},strokeRoundRect:function(i,f,j,k,l){var m=i+l,o=i+j,r=f+l;k=f+k;this.beginPath();this.arc(m,r,l,b,h,false);this.lineTo(j-l+i,f);this.arc(o-l,r,l,h,d,false);this.lineTo(o,k-l);this.arc(o-l,k-l,l,d,e,false);this.lineTo(m,k);this.arc(m,k-l,l,e,b,false);this.lineTo(i,r);this.stroke()},
drawRoundRect:function(i,f,j,k,l){var m=i+l,o=i+j,r=f+l;k=f+k;this.beginPath();this.arc(m,r,l,b,h,false);this.lineTo(j-l+i,f);this.arc(o-l,r,l,h,d,false);this.lineTo(o,k-l);this.arc(o-l,k-l,l,d,e,false);this.lineTo(m,k);this.arc(m,k-l,l,e,b,false);this.lineTo(i,r);this.stroke();this.fill()},drawRect:function(i,f,j,k){this.beginPath();this.rect(i,f,j,k);this.stroke();this.fill()},fillCircle:function(i,f,j){this.beginPath();this.arc(i,f,j,0,Math.PI*2,false);this.fill()},write:function(i,f,j,k){k!=null?
this.fillText(i,f,j,k):this.fillText(i,f,j)}});a.textBaseline=js.canvas.TextBaseline.TOP;return a}},"js.canvas.Canvas");js.canvas.Canvas.BUTT="butt";js.canvas.Canvas.ROUND="round";js.canvas.Canvas.SQUARE="square";js.canvas.Canvas.CAP={BUTT:js.canvas.Canvas.BUTT,ROUND:js.canvas.Canvas.ROUND,SQUARE:js.canvas.Canvas.SQUARE};js.canvas.Canvas.BEVEL="bevel";js.canvas.Canvas.MITER="miter";js.canvas.Canvas.JOIN={ROUND:js.canvas.Canvas.ROUND,BEVEL:js.canvas.Canvas.BEVEL,MITER:js.canvas.Canvas.MITER};
js.canvas.Canvas.REPEAT="repeat";js.canvas.Canvas.REPEAT_X="repeat-x";js.canvas.Canvas.REPEAT_Y="repeat-y";js.canvas.Canvas.NO_REPEAT="no-repeat";js.canvas.Canvas.PATTERN={REPEAT:js.canvas.Canvas.REPEAT,REPEAT_X:js.canvas.Canvas.REPEAT_X,REPEAT_Y:js.canvas.Canvas.REPEAT_Y,NO_REPEAT:js.canvas.Canvas.NO_REPEAT};js.canvas.TextBaseline={TOP:"top",HANGING:"hanging",MIDDLE:"middle",ALPHABETIC:"alphabetic",IDEOGRAPHIC:"ideographic",BOTTON:"bottom"};
js.canvas.CompositeOperation={DEFAULT:"source-over",SOURCE_OVER:"source-over",SOURCE_IN:"source-in",SOURCE_OUT:"source-out",SOURCE_ATOP:"source-atop",DESTINATION_OVER:"destination-over",DESTINATION_IN:"destination-in",DESTINATION_OUT:"destination-out",DESTINATION_ATOP:"destination-atop",LIGHTER:"lighter",DARKER:"darker",XOR:"xor",COPY:"copy"};jsool.namespace("js.flux.laf");js.flux.laf.Soft={FONT_COLOR:"#000000",FONT_FACE:"Tahoma",FONT_SIZE:12,BUTTON_BODY_COLOR:"#BBCCFF",BUTTON_BODY_PRESSED:"#EFF3FA",BUTTON_BORDER_COLOR:"#6688EE",BUTTON_BORDER_FOCUS:"#6688EE",BUTTON_BORDER_OVER:"#6688EE",BUTTON_BORDER_RADIUS:2,BUTTON_BORDER_WIDTH:1,CONTAINER_BODY_COLOR:"#FFFFFF",CONTAINER_BORDER_COLOR:"#898C95",CONTAINER_BORDER_RADIUS:2,CONTAINER_BORDER_WIDTH:1,CHECKBOX_CHECK:"#D3DBEA",SELECTION:"#C8E9FB"};jsool.namespace("js.flux");
js.flux.Component=$extends(js.util.Observable,{cons:function(){this.addEvent(["click","mouseup","mousedown","mouseover","mouseout","keypress","mousemove"]);this.name=this.type},x:0,y:0,width:0,height:0,parent:null,visible:true,canFocus:false,name:"",getName:function(){return this.name},contains:function(a,b){return a>this.x&&a<this.x+this.width&&b>this.y&&b<this.y+this.height},getComponentAt:function(a,b){return a>this.x&&a<this.x+this.width&&b>this.y&&b<this.y+this.height?this:null},setParent:function(a){this.parent&&
this.parent.remove(this);this.parent=a},getParent:function(){return this.parent},getX:function(){return this.x},getY:function(){return this.y},setX:function(a){this.x=a},setY:function(a){this.y=a},setWidth:function(a){this.width=a},setHeight:function(a){this.height=a},getWidth:function(){return this.width},getHeight:function(){return this.height},setVisible:function(a){this.visible=a},isVisible:function(){return this.visible},updateUI:function(a){if(this.visible){this.paint(a);this.dirty=true}},setSize:function(a,
b){this.width=a;this.height=b},setBounds:function(a,b,d,e){this.x=a;this.y=b;this.width=d;this.height=e},setPosition:function(a,b){this.x=a;this.y=b},getBounds:function(){return{x:this.x,y:this.y,width:this.width,height:this.height}},paint:jsool.emptyFn,getRealPosition:function(){if(this.parent){var a=this.parent.getRealPosition();return{x:parseInt(this.x)+a.x,y:parseInt(this.y)+a.y}}else return{x:parseInt(this.x),y:parseInt(this.y)}}},"js.flux.Component");jsool.namespace("js.flux");js.flux.RootContainer=$extends(js.flux.Container,{paint:function(){},updateUI:function(a){if(this.children.length>0)for(var b=0,d;d=this.children[b++];)if(d.isVisible()){a.save();d.updateUI(a);a.restore()}}},"js.flux.RootContainer");jsool.namespace("js.flux");
js.flux.Button=$extends(js.flux.Component,{cons:function(a){if(String.isString(a))this.text=a},width:70,height:20,text:"button",mouseover:false,pressed:false,focused:false,canFocus:true,paintOver:false,setText:function(a){if(String.isString(a))this.text=a},paint:function(a){var b=js.flux.UIManager.laf,d=b.FONT_SIZE,e=b.BUTTON_BORDER_RADIUS,h=this.x,i=this.y,f=this.width,j=this.height,k=this.text;a.fillStyle=this.pressed?b.BUTTON_BODY_PRESSED:b.BUTTON_BODY_COLOR;a.strokeStyle=b.BUTTON_BORDER_COLOR;
a.lineWidth=b.BUTTON_BORDER_WIDTH;a.drawRect(h+1,i+1,f-2,j-2,e);e=a.measureText(k).width;e=Math.max(0,(f-e)/2);var l=Math.max(0,(j-d)/2);a.textBaseline=js.canvas.TextBaseline.TOP;a.font=d+"px "+b.FONT_FACE;a.fillStyle=b.FONT_COLOR;a.fillText(k,h+e+1,i+l+1,f-2);if(!this.pressed)if(this.mouseover||this.paintOver){a.lineCap=js.canvas.Canvas.SQUARE;a.strokeStyle=b.BUTTON_BORDER_OVER;a.beginPath();a.rect(h+2,i+2,f-4,j-4);a.stroke();this.paintOver=false}else if(this.focused||this.paintFocus){a.lineCap=
js.canvas.Canvas.SQUARE;a.strokeStyle=b.BUTTON_BORDER_FOCUS;a.beginPath();a.rect(h+2,i+2,f-4,j-4);a.stroke()}},onmouseover:function(a,b){if(b==this&&!this.mouseover)this.paintOver=this.mouseover=true},onmouseout:function(a,b){if(b==this&&this.mouseover)this.pressed=this.mouseover=false},onmousedown:function(a,b){if(b==this&&!this.pressed)this.pressed=true},onmouseup:function(a,b){if(b==this&&this.pressed)this.pressed=false},onfocus:function(){this.focused=true},onlostfocus:function(){this.focused=
false}},"js.flux.Button");jsool.namespace("js.flux");js.flux.ToggleButton=$extends(js.flux.Button,{onmousedown:jsool.emptyFn,onmouseup:jsool.emptyFn,onclick:function(a,b){if(b==this)this.pressed=!this.pressed},onmouseout:function(a,b){if(b==this&&this.mouseover)this.mouseover=false}},"js.flux.ToggleButton");jsool.namespace("js.flux");js.flux.CheckBox=$extends(js.flux.ToggleButton,{paint:function(a){var b=js.flux.UIManager.laf;a.lineWidth=b.BUTTON_BORDER_WIDTH;a.lineStyle=b.BUTTON_BORDER_COLOR;a.fillStyle="white";a.beginPath();a.rect(this.x,this.y,10,10);a.stroke();a.fill();if(this.pressed){a.beginPath();a.fillStyle=b.CHECKBOX_CHECK;a.rect(this.x+1,this.y+1,8,8);a.fill()}},check:function(){this.pressed=true}},"js.flux.CheckBox");jsool.namespace("js.flux");
js.flux.UIManager=function(){function a(){i.set("width",window.innerWidth);i.set("height",window.innerHeight);t.height=window.innerHeight;t.width=window.innerWidth;t.x=0;t.y=0;v=true;h()}function b(){if(l){l=false;j=window.setInterval(e,o)}}function d(){if(!l){l=true;window.clearInterval(j)}}function e(){if(!m)if(v){r=0;v=false;h()}else{r++;if(r>=z){l||d();r=0}}}function h(){try{t.updateUI(f)}catch(q){throw new js.core.Exception(q.toString());}}var i,f,j,k=false,l=true,m=false,o=50,r=0,z=5,v=false,
w=null,u=null,t=null,y=0,x=function(q){if(m)return false;var n,p;n=jsool.isIE?{x:q.clientX+document.body.scrollLeft,y:q.clientY+document.body.scrollTop}:{x:q.pageX,y:q.pageY};if((p=t.getComponentAt(n.x,n.y))&&p!=t){if(q.type==="mousemove"){y--;if(y>=0)return false;y=3;if(u!=p){n={x:n.x,y:n.y,type:"mouseout",source:p,timestamp:q.timestamp};u&&u.fireEvent(n,u);n.type="mouseover";p.fireEvent(n,p)}u=p}else{n=jsool.apply({},n,q);p.fireEvent(n,p);if(p.canFocus&&(q.type==="click"||q.type==="dblclick")){if(w){n.type=
"lostfocus";w.fireEvent(n,p)}n.type="focus";w=p;p.fireEvent(n,p)}}v=true;l&&!m&&b();return true}if(u){u.fireEvent(jsool.apply({},{x:n.x,y:n.y,type:"mouseout"},q),u);u=null;return true}return false};return{add:function(q){if(!q.instanceOf(js.flux.Component))throw new js.core.Exception("Illegal argument: "+q);if(!k){i=new js.canvas.Canvas;f=i.getContext();i.setClass("flux-proxy");js.dom.Element.BODY.append(i);window.addEventListener?window.addEventListener("resize",a,false):window.attachEvent("onresize",
a);t=new js.flux.RootContainer;a();var n=js.core.EventManager,p=i.dom;n.on(p,"click",x);n.on(p,"dblclick",x);n.on(p,"mouseup",x);n.on(p,"mousedown",x);n.on(p,"mousemove",x);k=true;m||b()}t.add(q)},update:function(){v=true;l&&!m&&b()},start:b,stop:d,getLookAndFeel:function(){},requestFocus:function(q){if(q.instanceOf(js.flux.Component))w=q},getFocused:function(){return w},lock:function(){m=true;d()},unlock:function(){m=false;v&&b()},laf:jsool.laf||js.flux.laf.Soft}}();jsool.namespace("js.flux");js.flux.Layout=$extends(js.core.Object,{layoutContainer:jsool.emptyFn,addLayoutComponent:jsool.emptyFn},"js.flux.Layout");jsool.namespace("js.flux");
js.flux.BorderLayout=$extends(js.flux.Layout,{vSpace:2,hSpace:2,layoutContainer:function(a){var b,d=this.vSpace*2,e=this.hSpace*2;if(b=this.TOP){b.x=this.vSpace;b.y=this.hSpace;b.width=a.width-e}if(b=this.BOTTOM){b.x=this.hSpace;b.y=a.height-b.height-this.vSpace;b.width=a.width-e}var h=a.height-(this.TOP?this.TOP.height+d:0)-(this.BOTTOM?this.BOTTOM.height+d:0)-d;d=(this.TOP?this.TOP.height+d:0)+this.vSpace;if(b=this.LEFT){b.x=this.hSpace;b.y=d;b.height=h}if(b=this.RIGHT){b.x=a.width-b.width-this.hSpace;
b.y=d;b.height=h}if(b=this.CENTER){a=a.width-e;a-=this.LEFT?this.LEFT.width+e:0;a-=this.RIGHT?this.RIGHT.width+e:0;b.x=0+(this.LEFT?this.LEFT.width+e:0)+this.hSpace;b.y=d;b.width=a;b.height=h}},addLayoutComponent:function(a,b){if(b===js.flux.BorderLayout.TOP)this.TOP=a;if(b===js.flux.BorderLayout.BOTTOM)this.BOTTOM=a;if(b===js.flux.BorderLayout.LEFT)this.LEFT=a;if(b===js.flux.BorderLayout.RIGHT)this.RIGHT=a;if(b===js.flux.BorderLayout.CENTER)this.CENTER=a},setVSpace:function(a){this.vSpace=a},setHSpace:function(a){this.hSpace=
a}},"js.flux.BorderLayout");js.flux.BorderLayout.TOP="TOP";js.flux.BorderLayout.BOTTOM="BOTTOM";js.flux.BorderLayout.LEFT="LEFT";js.flux.BorderLayout.RIGHT="RIGHT";js.flux.BorderLayout.CENTER="CENTER";jsool.namespace("js.flux");
js.flux.RowLayout=$extends(js.flux.Layout,{hSpace:4,vSpace:4,ltr:true,layoutContainer:function(a){var b=null,d=null,e=a.height-2*this.vSpace,h=a.children;if(h.length>0){d=h[0];if(this.ltr){d.x=this.hSpace;b=d.x+d.width}else{d.x=a.width-this.hSpace-d.width;b=d.x-this.hSpace}d.y=this.vSpace;d.height=e}for(a=1;d=h[a++];){if(this.ltr){d.x=b+this.hSpace;b=d.x+d.width}else{d.x=b-d.width;b=d.x-this.hSpace}d.y=this.vSpace;d.height=e}},setVSpace:function(a){this.vSpace=a},setHSpace:function(a){this.hSpace=a},
setLtr:function(a){if(a!==this.lrt&&typeof a==="boolean"){this.ltr=a;js.flux.UIManager.update()}}},"js.flux.RowLayout");jsool.namespace("js.flux");js.flux.ColLayout=$extends(js.flux.Layout,{hSpace:4,vSpace:4,layoutContainer:function(a){var b=null,d=null,e=a.width-2*this.hSpace;a=a.children;if(a.length>0){d=a[0];d.x=this.hSpace;d.y=this.vSpace;d.width=e;b=d.y+d.height}for(var h=1;d=a[h++];){d.y=b+this.vSpace;b=d.y+d.height;d.x=this.hSpace;d.width=e}},setVSpace:function(a){this.vSpace=a},setHSpace:function(a){this.hSpace=a}},"js.flux.ColLayout");jsool.namespace("js.flux");
js.flux.SpringLayout=$extends(js.flux.Layout,{constraints:null,cyclicReference:null,cyclicSprings:null,acyclicSprings:null,cons:function(){this.constraints=new js.util.HashMap;this.cyclicReference=js.flux.Spring.constant(Number.MIN_VALUE);this.cyclicSprings={};this.acyclicSprings={}},resetCyclicStatuses:function(){this.cyclicSprings={};this.acyclicSprings={}},setParent:function(a){this.resetCyclicStatuses();var b=this.getConstraints(a);b.setX(js.flux.Spring.constant(0));b.setY(js.flux.Spring.constant(0));
var d=b.getWidth();d&&d.instanceOf(js.flux.WidthSpring)&&d.component==a&&b.setWidth(js.flux.Spring.constant(0,0,Number.MAX_VALUE));(d=b.getHeight())&&d.instanceOf(js.flux.HeightSpring)&&d.component==a&&b.setHeight(js.flux.Spring.constant(0,0,Number.MAX_VALUE))},isCyclic:function(a){if(a){if(this.cyclicSprings[a.hashCode()])return true;if(this.acyclicSprings[a.hashCode()])return false;this.cyclicSprings[a.hashCode()]=a;var b=a.isCyclic(this);if(!b){this.acyclicSprings[a.hashCode()]=a;delete this.cyclicSprings[a.hashCode()]}return b}else return null},
abandonCycles:function(a){return this.isCyclic(a)?this.cyclicReference:s},removeLayoutComponent:function(a){this.constraints.remove(a)}},"js.flux.SpringLayout");js.flux.Spring=$extends(js.core.Object,{UNSET:Number.MIN_VALUE,range:function(a){return a?this.getPreferredValue()-this.getMinimumValue():this.getMaximumValue()-this.getPreferredValue()},getStrain:function(){return(this.getValue()-this.getPreferredValue())/this.range(this.getValue()<this.getPreferredValue())},setStrain:function(a){this.setValue(this.getPreferredValue()+a*this.range(a<0))},getValue:function(){return this.size!=this.UNSER?this.size:this.getPreferredValue()},setValue:function(a){if(this.size!=
a)a==this.UNSET?this.clear():this.setNonClearValue(a)},clear:function(){this.size=this.UNSET},setNonClearValue:function(a){this.size=a},isCyclic:function(){return false}},"js.flux.Spring");
js.flux.StaticSpring=$extends(js.flux.Spring,{cons:function(a,b,d){this.min=a;this.pref=b;this.max=d},toString:function(){return"StaticSpring ["+this.min+", "+this.pref+", "+this.max+"]"},getMinimumValue:function(){return this.min},getMaximumValue:function(){return this.max},getPreferredValue:function(){return this.pref}},"js.flux.StaticSpring");
js.flux.NegativeSpring=$extends(js.flux.Spring,{cons:function(a){this.spring=a},getMinimumValue:function(){return-this.spring.getMinimumValue()},getMaximumValue:function(){return-this.spring.getMaximumValue()},getPreferredValue:function(){return-this.spring.getPreferredValue()},getValue:function(){return-this.spring.getValue()},setValue:function(a){this.spring.setValue(-a)},isCyclic:function(a){return this.spring.isCyclic(a)}},"js.flux.NegativeSpring");
js.flux.ScaleSpring=$extends(js.flux.Spring,{cons:function(a,b){this.spring=a;this.factor=b},getMinimumValue:function(){return Math.round((this.factor<0?this.spring.getMaximumValue():this.spring.getMinimumValue())*this.factor)},getMaximumValue:function(){return Math.round((this.factor<0?this.spring.getMinimumValue():this.spring.getMaximumValue())*this.factor)},getPreferredValue:function(){return Math.round(this.spring.getPreferredValue()*this.factor)},getValue:function(){return Math.round(this.spring.getValue()*
this.factor)},setValue:function(a){a==this.UNSET?this.spting.setValue(this.UNSET):this.spting.setValue(Math.round(a/this.factor))},isCyclic:function(a){return this.spring.isCyclic(a)}},"js.flux.ScaleSpring");js.flux.WidthSpring=$extends(js.flux.Spring,{component:null,cons:function(a){this.component=a},getMinimumValue:function(){return this.component.width},getMaximumValue:function(){return this.component.width},getPreferredValue:function(){return this.component.width}},"js.flux.WidthSpring");
js.flux.HeightSpring=$extends(js.flux.Spring,{component:null,cons:function(a){this.component=a},getMinimumValue:function(){return this.component.height},getMaximumValue:function(){return this.component.height},getPreferredValue:function(){return this.component.height}},"js.flux.HeightSpring");
js.flux.SpringMap=$extends(js.flux.Spring,{spring:null,cons:function(a){this.spring=a},map:jsool.emptyFn,inv:jsool.emptyFn,getMinimumValue:function(){return this.map(this.spring.getMinimumValue())},getMaximumValue:function(){return this.map(this.spring.getMaximumValue())},getPreferredValue:function(){return this.map(this.spring.getPreferredValue())},getValue:function(){return this.map(this.spring.getValue())},setValue:function(a){a==this.UNSET?this.spring.setValue(this.UNSET):this.spring.setValue(this.inv(a))},
isCyclic:function(a){return this.spring.isCyclic(a)}},"js.flux.SpringMap");
js.flux.CompoundSpring=$extends(js.flux.StaticSpring,{s1:null,s2:null,ccons:function(a,b){this.$super(this.UNSET);this.s1=a;this.s2=b},toString:function(){return"CompoundSpring of "+this.s1+" and "+this.s2},clear:function(){this.$super.clear();this.min=this.max=this.pref=this.UNSET;this.s1.setValue(this.UNSET);this.s2.setValue(this.UNSET)},op:jsool.emptyFn,getMinimumValue:function(){if(this.min==this.UNSET)this.min=this.op(this.s1.getMinimumValue(),this.s2.getMinimumValue());return this.min},getMaximumValue:function(){if(this.max==
this.UNSET)this.max=this.op(this.s1.getMaximumValue(),this.s2.getMaximumValue());return this.max},getPreferredValue:function(){if(this.pref==this.UNSET)this.pref=this.op(this.s1.getPreferredValue(),this.s2.getPreferredValue());return this.pref},getValue:function(){if(this.size==this.UNSET)this.size=this.op(this.s1.getValue(),this.s2.getValue());return this.size},isCyclic:function(a){return a.isCyclic(this.s1)||a.isCyclic(this.s2)}},"js.flux.CompoundSpring");
js.flux.SumSpring=$extends(js.flux.CompoundSpring,{ccons:function(a,b){this.$super(a,b)},op:function(a,b){return a+b},setNonClearValue:function(a){this.$super.setNonClearValue(a);this.s1.setStrain(this.getStrain());this.s2.setValue(a-this.s1.getValue())}},"js.flux.SumSpring");
js.flux.MaxSpring=$extends(js.flux.CompoundSpring,{ccons:function(a,b){this.$super(a,b)},op:function(a,b){return Math.max(a,b)},setNonClearValue:function(a){this.$super.setNonClearValue(a);this.s1.setValue(a);this.s2.setValue(a)}},"js.flux.MaxSpring");
jsool.apply(js.flux.Spring,{constrant:function(){return arguments.length>1?new js.flux.StaticSpring(arguments[0],arguments[1],arguments[2]):new js.flux.StaticSpring(arguments[0],arguments[0],arguments[0])},minus:function(a){return new js.flux.NegativeSpring(a)},sum:function(a,b){return new js.flux.SumSpring(a,b)},max:function(a,b){return new js.flux.MaxSpring(a,b)},diferrence:function(a,b){return new js.flux.SumSpring(a,new js.flux.NegativeSpring(b))},scale:function(a,b){return new js.flux.ScaleSpring(a,
b)},width:function(a){return new js.flux.WidthSpring(a)},height:function(a){return new js.flux.HeightSpring(a)}});js.flux.SpringContraint=$extends(js.core.Object,{x:null,y:null,width:null,height:null,east:null,south:null,horizontalCenter:null,verticalCenter:null,baseline:null,horizontalHistory:null,verticalHistory:null,component:null,ALL_HORIZONTAL:["WEST","WIDTH","EAST","HORIZONTAL_CENTER"],ALL_VERTICAL:["NORTH","HEIGHT","SOUTH","VERTICAL_CENTER","BASELINE"],cons:function(a,b,d,e){this.horizontalHistory=[];this.verticalHistory=[];if(a)if((this.component=a)&&b){this.setX(a);this.setY(b);if(d&&e){this.setHeight(e);
this.setWidth(d)}}},pushConstraint:function(a,b,d){var e=true,h=d?this.horizontalHistory:this.verticalHistory;if(h.contains(a)){h.remove(a);e=false}else if(h.length==2&&b!=null){h.splice(0,1);e=false}b!=null&&h.push(a);if(!e){a=d?this.horizontalHistory:this.verticalHistory;for(b=0;d=a[b++];)h.contains(d)||this.setConstraint(d,null)}},sum:function(a,b){return a&&b?js.flux.Spring.sum(a,b):null},difference:function(a,b){return a&&b?js.flux.Spring.difference(a,b):null},scale:function(a,b){return a?js.flux.Spring.scale(a,
b):null},getBaselineFromHeight:function(a){if(a<0)return-this.component.getBaseline(c.getPreferredSize().width,-a);return this.component.getBaseline(c.getPreferredSize().width,a)},defined:function(a,b,d){return a.contains(b)&&a.contains(d)},setX:function(a){this.x=a;pushConstraint("WEST",a,true)},getX:function(){if(!this.x)if(this.defined(this.horizontalHistory,"EAST","WIDTH"))this.x=this.difference(this.east,this.width);else if(this.defined(this.horizontalHistory,"HORIZONTAL_CENTER","WIDTH"))this.x=
this.difference(this.horizontalCenter,this.scale(this.width,0.5));else if(this.defined(this.horizontalHistory,"HORIZONTAL_CENTER","EAST"))this.x=this.difference(this.scale(this.horizontalCenter,2),this.east);return this.x},setY:function(a){this.y=a;pushConstraint("NORTH",a,false)},getY:function(){if(!this.y)if(this.defined(this.verticalHistory,"SOUTH","HEIGHT"))this.y=this.difference(this.south,this.height);else if(this.defined(this.verticalHistory,"VERTICAL_CENTER","HEIGHT"))this.y=this.difference(this.verticalCenter,
this.scale(this.height,0.5));else if(this.defined(this.verticalHistory,"VERTICAL_CENTER","SOUTH"))this.y=this.difference(this.scale(this.verticalCenter,2),this.south);return this.y},setWidth:function(a){this.width=a;this.pushConstraint("WIDTH",a,true)},getWidth:function(){if(!this.width)if(this.horizontalHistory.contains("EAST"))this.width=this.difference(this.east,this.getX());else if(this.horizontalHistory.contains("HORIZONTAL_CENTER"))this.width=this.scale(this.difference(this.horizontalCenter,
this.getX()),2);return this.width},setHeight:function(a){this.height=a;this.pushConstraint("HEIGHT",a,false)},getHeight:function(){if(!this.height)if(this.verticalHistory.contains("SOUTH"))this.height=this.difference(this.south,this.getY());else if(this.verticalHistory.contains("VERTICAL_CENTER"))this.height=this.scale(this.difference(this.verticalCenter,this.getY()),2);return this.height},setEast:function(a){this.east=a;this.pushConstraint("EAST",a,true)},getEast:function(){if(!this.east)this.east=
this.sum(this.getX(),this.getWidth());return this.east},setSouth:function(a){this.south=a;this.pushConstraint("SOUTH",a,false)},getSouth:function(){if(!this.south)this.south=this.sum(this.getY(),this.getHeight());return this.south},getHorizontalCenter:function(){if(this.horizontalCenter==null)this.horizontalCenter=this.sum(this.getX(),this.scale(this.getWidth(),0.5));return this.horizontalCenter},setHorizontalCenter:function(a){this.horizontalCenter=a;this.pushConstraint("HORIZONTAL_CENTER",a,true)},
getVerticalCenter:function(){if(this.verticalCenter==null)this.verticalCenter=this.sum(this.getY(),this.scale(this.getHeight(),0.5));return this.verticalCenter},setVerticalCenter:function(a){this.verticalCenter=a;this.pushConstraint("VERTICAL_CENTER",a,false)},setConstraint:function(a,b){switch(a){case "WEST":this.setX(b);break;case "NORTH":this.setY(b);break;case "EAST":this.setEast(b);break;case "SOUTH":this.setSouth(b);break;case "HORIZONTAL_CENTER":this.setHorizontalCenter(b);break;case "WIDTH":this.setWidth(b);
break;case "HEIGHT":this.setHeight(b);break;case "VERTICAL_CENTER":this.setVerticalCenter(b)}},getConstraint:function(a){return a=="WEST"?this.getX():a=="NORTH"?this.getY():a=="EAST"?this.getEast():a=="SOUTH"?this.getSouth():a=="WIDTH"?this.getWidth():a=="HEIGHT"?this.getHeight():a=="HORIZONTAL_CENTER"?this.getHorizontalCenter():a=="VERTICAL_CENTER"?this.getVerticalCenter():null},reset:function(){for(var a=[this.x,this.y,this.width,this.height,this.east,this.south,this.horizontalHistory,this.verticalHistory],
b=0,d;d=a[b++];)d&&d.setValue(Number.MIN_VALUE)}},"js.flux.SpringContraint");js.flux.SpringProxy=$extends(js.flux.Spring,{edgeName:null,component:null,layout:null,cons:function(a,b,d){this.edgeName=a;this.component=b;this.layout=d},getConstraint:function(){return this.layout.getConstraints(this.component).getConstraint(this.edgeName)},getMinimumValue:function(){return this.getConstraint().getMinimumValue()},getPreferredValue:function(){return this.getConstraint().getPreferredValue()},getMaximumValue:function(){return this.getConstraint().getMaximumValue()},getValue:function(){return this.getConstraint().getValue()},
setValue:function(a){return this.getConstraint().setValue(a)},isCyclic:function(a){return a.isCyclic(this.getConstraint())},toString:function(){return"SpringProxy for "+this.edgeName+" edge of "+this.component.getName()+"."}},"js.flux.SpringProxy");